package com.chronos.reminder.core

// Code generated by scripts/sync-constants.py — DO NOT EDIT manually.
// Run  python scripts/sync-constants.py  after editing constants.yaml.

object AppConstants {

    const val VERSION = "1.2.7"

    object Urls {
        const val WEB_APP        = "https://chronosrmd.com"
        const val API            = "https://api.chronosrmd.com"
        const val DOCS           = "https://docs.chronosrmd.com"
        const val STATUS         = "https://status.chronosrmd.com/status/chronos"
        const val GITHUB         = "https://github.com/Eric-Philippe/Chronos-Reminder"
        const val DISCORD_INVITE = "https://discord.gg/m3MsM922QD"
        const val CONTACT        = "https://chronosrmd.com/contact"
    }
}
