// Code generated by scripts/sync-constants.py — DO NOT EDIT manually.
// Run  python scripts/sync-constants.py  after editing constants.yaml.

export const VERSION = "1.2.7";

export const URLS = {
  webApp:        "https://chronosrmd.com",
  api:           "https://api.chronosrmd.com",
  docs:          "https://docs.chronosrmd.com",
  status:        "https://status.chronosrmd.com/status/chronos",
  github:        "https://github.com/Eric-Philippe/Chronos-Reminder",
  discordInvite: "https://discord.gg/m3MsM922QD",
  contact:       "https://chronosrmd.com/contact",
} as const;
