package config

// Code generated by scripts/sync-constants.py — DO NOT EDIT manually.
// Run  python scripts/sync-constants.py  after editing constants.yaml.

const (
	Version = "1.2.1"

	URLWebApp       = "https://chronosrmd.com"
	URLAPI          = "https://api.chronosrmd.com"
	URLDocs         = "https://docs.chronosrmd.com"
	URLStatus       = "https://status.chronosrmd.com/status/chronos"
	URLGitHub       = "https://github.com/Eric-Philippe/Chronos-Reminder"
	URLDiscordInvite = "https://discord.gg/m3MsM922QD"
	URLContact      = "https://chronosrmd.com/contact"

	EmailNoreply = "noreply@noreply.chronosrmd.com"
)
